name: GitHub Pages Deployment

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - run: npm ci
      - run: npm run build

      - name: List dist folder contents
        run: |
          echo "Listing dist folder:"
          ls -la ./dist
          if [ -d "./dist/cloud-slicer-docs" ]; then
            echo "Listing dist/cloud-slicer-docs folder:"
            ls -la ./dist/cloud-slicer-docs
          fi

      - uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/cloud-slicer-docs

      - id: deployment
        uses: actions/deploy-pages@v4
